---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  labels:
    app: flask
data:
  env: production
  app.settings: production.env
  redis.url: redis://redis:6379
  secret.key: foundation