---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
  labels:
    app: flask-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: flask
  type: LoadBalancer