---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask
  namespace: default
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: multivac-flask
        image: gcr.io/unbabel-sre-theo/multivac:latest
        imagePullPolicy: Always
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              key: FLASK_ENV
              name: flask-config
        - name: APP_SETTINGS
          valueFrom:
            configMapKeyRef:
              key: APP_SETTINGS
              name: flask-config
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mondodb-credentials
              key: url