---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: multivac-flask
        image: gcr.io/unbabel-sre-theo/multivac:latest
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              key: env
              name: flask-config
        - name: APP_SETTINGS
          valueFrom:
            configMapKeyRef:
              key: app.settings
              name: flask-config
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              key: redis.url
              name: flask-config
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: secret.key
              name: flask-config
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mondodb-credentials
              key: url