---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    role: db
spec:
  replicas: 1
  selector:
    matchLabels:
      role: db
  serviceName: mongo
  template:
    metadata:
      labels:
        role: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: bitnami/mongodb:4.0
          volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
          env:
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mondodb-credentials
                  key: database
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mondodb-credentials
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mondodb-credentials
                  key: password

  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 10Gi