---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    role: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      role: cache
  template:
    metadata:
      labels:
        role: cache
    spec:
      containers:
      - name: multivac-redis
        image: redis:3